Repository songkg7/o2, pull requests merged in 2024-12, with the labels that each got.

#407 feat: Add relative_url filter support for Jekyll image paths
  src/ResourceLinkConverter.ts
  src/jekyll/settings/JekyllSettings.ts
  src/settings.ts
  src/tests/ResourceLinkConverter.test.ts
Labels: size/M

#406 add a relative_url toggle for support Jekyll Liquid Filters
  .eslintignore
  .eslintrc
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/auto_assign.yml
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/workflows/auto-approve.yml
  .github/workflows/auto-assign-action.yml
  .github/workflows/auto-release.yml
  .github/workflows/ci.yml
  .github/workflows/linter.yml
  .prettierrc
  CODE_OF_CONDUCT.md
  README.md
  esbuild.config.mjs
  eslint.config.mjs
  jest.config.js
  manifest.json
  package-lock.json
  package.json
  src/CalloutConverter.ts
  src/CommentsConverter.ts
  src/CurlyBraceConverter.ts
  src/FootnotesConverter.ts
  src/FrontMatterConverter.ts
  src/ResourceLinkConverter.ts
  src/WikiLinkConverter.ts
  src/core/ConverterChain.ts
  src/core/ObsidianRegex.ts
  src/core/validation.ts
  src/docusaurus/DateExtractionPattern.ts
  src/docusaurus/docusaurus.ts
  src/docusaurus/settings/DocusaurusSettings.ts
  src/jekyll/chirpy.ts
  src/jekyll/settings/JekyllSettings.ts
  src/main.ts
  src/settings.ts
  src/tests/CalloutConverter.test.ts
  src/tests/ConverterChain.test.ts
  src/tests/DateExtractionPattern.test.ts
  src/tests/EmbedsConverter.test.ts
  src/tests/FrontMatterConverter.test.ts
  src/tests/ResourceLinkConverter.test.ts
  src/tests/WikiLinkConverter.test.ts
  src/utils.ts
  sweep.yaml
  tsconfig.json
  version-bump.mjs
  versions.json
Labels: chirpy, size/XXL

#411 ci: disable unnecessary linter settings
  .github/workflows/linter.yml
Labels: size/XS

#412 fix(ci): codecov report
  .github/workflows/ci.yml
Labels: size/XS

#410 feat: Moving the finished note to something other than _posts
  src/jekyll/chirpy.ts
  src/jekyll/settings/JekyllSettings.ts
Labels: size/S, in review
